### ISSUE TITLE
PDF save failure in new tabs in Chrome

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#289]
https://www.ajronline.org/doi/abs/10.2214/ajr.157.2.1853823

Click the PDF link in Chrome and try to save in the new tab.

```
messaging.js:121 Uncaught (in promise) TypeError: Cannot read property 'saveAsWebpage' of undefined
    at Object.saveAsWebpage (inject/inject.js:558)
    at messageListener (messaging_inject.js:119)
    at messaging_inject.js:129
```

Cmd-clicking the Bitcoin PDF from the Google search results and trying to save fails too.

It works after reloading the PDF, or when following a normal PDF link that doesn't open in a new tab.

**Comment by adomasven** [comment]
Cannot reproduce. Maybe fixed in by Google?

**Comment by dstillman** [comment]
It seems to be intermittent for me. And when it fails, errors are actually logged in the page console, starting with this one:

```
Uncaught SyntaxError: Identifier 'ZOTERO_CONFIG' has already been declared
    at /Users/dan/Library/Application%20Support/Google/Chrome/Default/Extensions/ekhagklcjbdpajgpjgmbionohlpdbjgc/5.0.57_0/zotero_config.js:1
```

**Comment by dstillman** [comment]
I can still reproduce this easily, and it was reported here:

https://forums.zotero.org/discussion/comment/353859/#Comment_353859

I can fix it by changing a handful of `const` declarations to `var` — in zotero_config.js, inject/inject.jsx, and messages.js — which isn't, like, a great fix, but seems to work.

Can you think of any reason all the content scripts would be getting loaded twice? The fact that it's only happening for PDFs in new tabs, and only happening in Chrome, makes me think that this is some sort of bug in Chrome, but maybe there's something else I'm missing.
